#!/bin/bash

# Set some variables which are likely to change
URL="https://taskwarrior.org/download/task-2.5.1.tar.gz"
SUM="647faf0784aa8ebe48cba3e2061f79e1ddbf3e84"
FILE="task-2.5.1.tar.gz"
DIR="task-2.5.1"

# Generated variables
APP=`basename $1`
SRC="$1/source"

# Change to the source directory
cd "$SRC"

# Download source
echo "Downloading $FILE source..."
wget -q $URL

# Verify source sum
echo "Verifying hash for $FILE source..."
echo "$SUM  $FILE" > "sum-for-$FILE"
sha1sum $FILE > check-sum

# 0 return for no differences
diff "sum-for-$FILE" check-sum > /dev/null
DIFF="$?"

if [ ! $DIFF -eq 0 ]
then
  echo "Checksum on downloads failed to match - something wonky happened"
  echo "Exiting for safety reasons"
  exit 1
fi

# Extract source
echo "Extracting source to $SRC"
tar -xzf $FILE

# Leave the directory the source extracted to for the build script
echo "$SRC/$DIR" > dir-name
